---
- name: Lấy dữ liệu từ user2 → hiện lên trang web user1 (tiếng Việt đẹp)
  hosts: web
  become: yes
  tasks:
    - name: Lấy nội dung file từ user2
      slurp:
        src: /home/user2/myname.txt
      register: user2_data
      delegate_to: localhost
      become: yes
      become_user: user2

    - name: Hiển thị dữ liệu user2 lên trang web user1 (UTF-8 chuẩn)
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="vi">
          <head>
            <meta charset="UTF-8">
            <title>user1 Web Server</title>
            <style>
              body {font-family: "DejaVu Sans", "Arial Unicode MS", Arial; text-align: center; margin-top: 50px;}
              pre {background:#f0f0f0; padding:20px; font-size:18px; display:inline-block; text-align:left;}
            </style>
          </head>
          <body>
            <h1 style="color:red;">Hello World từ user1!</h1>
            <hr>
            <h2 style="color:blue;">Dữ liệu lấy từ user2 (Database Server):</h2>
            <pre>{{ user2_data.content | b64decode | string | regex_replace('\r', '') }}</pre>
            <p><small>Cập nhật lúc: {{ ansible_date_time.iso8601 }}</small></p>
          </body>
          </html>
        dest: /var/www/html/index.html
      notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
