---
- name: Cài Nginx + Hello cho User1
  hosts: web
  become: yes
  tasks:
    - apt:
        name: nginx
        state: present
        update_cache: yes
    - copy:
        content: "<h1 style='color: green'>Hello from User1!</h1>"
        dest: /var/www/html/index.html
